/* HealthWiz original (HealthWiz_Kingdom_5-4-3.html), part 2/7 — generated by tools/import-original.mjs; edit freely, but keep load order. */
const F=MENU.foods,DAYS=MENU.days;
const $=s=>document.querySelector(s),pad=n=>String(n).padStart(2,'0');
const ymd=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const today=()=>ymd(new Date()),nowT=()=>{const d=new Date();return pad(d.getHours())+':'+pad(d.getMinutes())};
let RNc=null; // v6 (§92): the last-n-days lists are built once per synchronous run, like IX() below
const rng=n=>{if(!RNc){RNc=new Map();queueMicrotask(()=>{RNc=null})}let a=RNc.get(n);if(!a)RNc.set(n,a=Array.from({length:n},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(n-1-i));return ymd(d)}));return a.slice()};
const esc=s=>String(s==null?'':s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
let mem=null;
const DEF=()=>({sv:HWSchema.V,q6:{f:{},w:{}},ex:{p:{}},xl:{},md:{last:{},day:{},seen:{},ms:{},log:[]},mg:{xp:{},n:{},h:[],c:{}},b:{},e:[],s:{kcal:2200,water:2000,sound:1,set:0},p:{w:60,h:165,age:16,sex:'m',act:1.375,days:3,goal:'m'},xp:0,claimed:{}});
let st=HWSchema.load(DEF); // v6: versioned load with migrations (js/v6-schema.js)
// v6 (§92): one action often saves several times (entry, XP, badge, quest…). SV still counts every save(), but storage
// is written once, at the end of that synchronous run, before the browser handles anything else.
// §88: if the write fails (storage full or blocked), superseded pre-upgrade copies are freed and the write retried;
// if it still fails, the user is told (again at most every 2 minutes) that the change is not saved on this device.
let SV=0,SVq=0,SVwarn=0;const save=()=>{SV++;if(!SVq){SVq=1;queueMicrotask(persist)}};
function persist(){SVq=0;const j=JSON.stringify(st),w=()=>localStorage.setItem('healthwiz',j);try{w();SVwarn=0;return}catch(e){}
  try{Object.keys(localStorage).filter(k=>k.startsWith('healthwiz_backup_pre-v')).forEach(k=>localStorage.removeItem(k));w();SVwarn=0;return}catch(e){}
  mem=st;if(Date.now()-SVwarn<120e3)return;SVwarn=Date.now();
  toast('⚠️ Your latest changes could not be saved on this device (storage is full or blocked). They stay in this tab until you close it. Download a backup in Settings → Backup now.');
  if(typeof HWEvents!=='undefined')HWEvents.emit('storage:failed',{bytes:j.length})}
const S={v:'welcome',meal:'breakfast',src:'d'+new Date().getDate(),q:'',sel:null,qty:1,pm:1,ck:'',cf:0,loc:0,cat:'MILD',rg:'w',sq:{ph:0,n:0},pb:{pace:1,on:0,k:0},fc:'all',tm:0};
const acts={},INP={},CH={};let UD=null,ac;
function sfx(f,d){if(!st.s.sound)return;try{ac=ac||new(window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')ac.resume();const o=ac.createOscillator(),g=ac.createGain();o.type='square';o.frequency.value=f||440;g.gain.value=.04;o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+(d||.1))}catch(e){}}
function toast(m){if(typeof HWPop!=='undefined')return HWPop.toast(m);const d=document.createElement('div');d.innerHTML=m;$('#toasts').appendChild(d);setTimeout(()=>d.remove(),3200)}
function spr(map,pal,sc){const c=document.createElement('canvas');c.width=map[0].length;c.height=map.length;const x=c.getContext('2d');map.forEach((r,y)=>[...r].forEach((ch,i)=>{if(pal[ch]){x.fillStyle=pal[ch];x.fillRect(i,y,1,1)}}));return '<img class="px" alt="" src="'+c.toDataURL()+'" width="'+c.width*sc+'" height="'+c.height*sc+'">'}
const HERO=sc=>'<img class="hero" alt="" src="'+KN+'" width="'+16*sc+'" style="height:auto">';
const HEART=sc=>spr(['.rr.rr.','rrrrrrr','rrrrrrr','.rrrrr.','..rrr..','...r...'],{r:'#e0483f'},sc);
const bar=(p,c)=>'<div class="bar" style="--c:'+c+'"><i style="width:'+Math.min(100,Math.max(0,p))+'%"></i></div>';
const LV=[['Beginner Adventurer',0],['Trail Walker',150],['Health Explorer',400],['Fitness Knight',800],['Wellness Hero',1400],['Sage of Balance',2200]];
function lvl(){let i=0;LV.forEach((l,k)=>{if(st.xp>=l[1])i=k});const n=LV[i+1];return{i,n:LV[i][0],lo:LV[i][1],hi:n?n[1]:0}}
function gain(x,m){const l0=lvl().i;st.xp+=x;st.xd=st.xd||{};st.xd[today()]=(st.xd[today()]||0)+x;save();toast('+'+x+' XP '+(m||''));sfx(660,.08);if(lvl().i>l0){toast('LEVEL UP! '+lvl().n);setTimeout(()=>sfx(880,.3),200)}}
// v6 (§92, step 24): entries grouped by category and day, built at most once per synchronous run (one render or
// one action) instead of scanning every entry on each of the thousands of A() calls a page makes. It is dropped at
// the end of the run, and rebuilt whenever st.e, its length or SV (every save()) changes, so it is never stale.
// Callers still get fresh arrays, in the original order.
let IXc=null;
function IX(){const e=st.e;if(IXc&&IXc.e===e&&IXc.n===e.length&&IXc.sv===SV)return IXc;if(!IXc)queueMicrotask(()=>{IXc=null});
  const c=new Map(),cd=new Map();for(const x of e){let a=c.get(x.c);if(!a){c.set(x.c,a=[]);cd.set(x.c,new Map())}a.push(x);const m=cd.get(x.c);let b=m.get(x.d);if(!b)m.set(x.d,b=[]);b.push(x)}
  return IXc={e,n:e.length,sv:SV,c,cd,all:null,lc:new Map(),dys:null}}
const ALL=()=>{const I=IX();if(!I.all)I.all=[...st.e].sort((a,b)=>(a.d+a.t).localeCompare(b.d+b.t));return I.all.slice()};
const LC=c=>{const I=IX();let a=I.lc.get(c);if(!a)I.lc.set(c,a=ALL().filter(x=>x.c===c));return a.slice()};
const A=(c,d)=>{const m=IX().cd.get(c),b=m&&m.get(d||today());return b?b.slice():[]};
const sum=(c,d)=>A(c,d).reduce((a,x)=>a+(+x.v||0),0);
const kc=d=>sum('food',d),wt=d=>sum('water',d),sp=d=>sum('stair',d);
const cl=d=>A('stair',d).reduce((a,x)=>a+(+x.m.climbs||0),0);
const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
// v6 (stairs refactor): heart rate comes from stair workouts only (before / after, typed in by the user; js/v6-stairs.js).
// Old 'pulse' entries stay in the save untouched but are no longer read here.
const hrv=(d,k)=>A('stair',d).map(x=>+(x.m||{})[k]).filter(v=>v>=30&&v<=220),hrS=d=>A('stair',d).filter(x=>x.m&&(+x.m.hrB||+x.m.hrA)).length;
const rest=d=>{const a=hrv(d,'hrB');return a.length?Math.round(avg(a)):null}; // before a workout
const hr=d=>{const a=hrv(d,'hrA');return a.length?Math.round(avg(a)):null}; // right after a workout
const str=d=>{const a=A('stress',d).map(x=>x.v);return a.length?+avg(a).toFixed(1):null};
function add(c,v,m,note,d,t,xp,msg){st.e.push({id:Date.now()+''+Math.floor(Math.random()*999),c,v,m:m||{},n:note||'',d:d||today(),t:t||nowT()});save();gain(xp==null?10:xp,msg);if(RGN[c])setTimeout(()=>toast(RGN[c]+' grows brighter ✨'),300)}
const bmi=()=>+(st.p.w/Math.pow(st.p.h/100,2)).toFixed(1);
const bcat=b=>b<18.5?'Underweight range':b<25?'Healthy weight range':b<30?'Overweight range':'Obesity range';
function score(d){const w=Math.min(1,wt(d)/st.s.water)*25,ms=new Set(A('food',d).map(x=>x.m.meal)).size,f=Math.min(1,ms/3)*20,s=Math.min(1,sp(d)/100)*25,p=A('pulse',d).length||hrS(d)?10:0,k=A('stress',d).length?10:0,c=kc(d),q=c>=st.s.kcal*.6&&c<=st.s.kcal*1.1?10:0;return Math.round(w+f+s+p+k+q)}
const quests=d=>QD(d).map(q=>[q.n,q.p>=1]);
function chart(v,lb,c,u,tg,tl){const vs=v.map(x=>+x||0),mx=Math.max(1,...vs,tg||0),lg=vs.filter(x=>x),av=lg.length?avg(lg):null,r=x=>Math.round(x*10)/10;
return '<div class="ch">'+(tg?'<b class="tg" style="bottom:calc(3px + (100% - 6px)*'+(tg/mx).toFixed(4)+')"><span>'+(tl||'target')+' '+r(tg)+'</span></b>':'')+v.map((x,i)=>'<div title="'+lb[i]+': '+(x==null||x===0?'-':r(x))+' '+u+'"><i style="height:'+(x?Math.max(4,x/mx*100):0)+'%;background:'+c+'"></i></div>').join('')+'</div>'+(lb.length<=7?'<div class="chl">'+lb.map(d=>'<span>'+(/^\d{4}-\d{2}-\d{2}$/.test(d)?DOW[new Date(d+'T12:00:00').getDay()]:esc(String(d).slice(0,3)))+'</span>').join('')+'</div>':'')+'<small>'+(av!=null?'avg '+r(av)+' '+u+' (logged days) · ':'')+'peak '+r(Math.max(0,...vs))+' '+u+'</small>'}
const MEALS=[['breakfast','Breakfast'],['morning','Morning Snack'],['lunch','Lunch'],['dinner','Dinner'],['night','Night Snack'],['sahur','Sahur'],['iftar','Iftar'],['moreh','Moreh']];
const MN=k=>(MEALS.find(m=>m[0]===k)||[0,k])[1];
const UNIT={food:'kcal',water:'ml',pulse:'BPM',stair:'steps',stress:'/10',bmi:'BMI',sleep:'h'};
function desc(e){const m=e.m;return e.c==='food'?esc(m.name)+' · '+(m.qty||1)+' srv'+(m.pm&&m.pm!=1?' @ '+m.pm+'× portion':'')+' · '+MN(m.meal)+(m.custom?' <span class="badge">Custom Food</span>':'')+(m.u?' <span class="badge">kcal by you</span>':'')+macLine(e):e.c==='pulse'?esc(m.st):e.c==='stair'?esc(m.loc)+' · '+m.climbs+'x'+m.steps:e.c==='stress'?esc(m.feel||'Stress check-in')+(m.end!=null?' → '+m.end+'/10':''):e.c==='water'?'Water':e.c==='sleep'?'Sleep · 🛏'+esc(m.bed||'')+' → ☀'+esc(m.wake||'')+' · score '+(m.score||0):'BMI'}
const row=(e,dt)=>'<div class="er"><span>'+(dt?e.d.slice(5)+' ':'')+e.t+'</span><span>'+desc(e)+(e.n?' <small>– '+esc(e.n)+'</small>':'')+'</span><b>'+e.v+' '+UNIT[e.c]+'</b><button class="sm g" aria-label="Edit" data-a="edit" data-id="'+e.id+'">✏️</button><button class="sm g" aria-label="Delete" data-a="del" data-id="'+e.id+'">🗑</button></div>';
const list=(c,d)=>{const a=A(c,d);return a.length?a.map(e=>row(e)).join(''):emp('🌱 THIS LAND IS QUIET','Log your first entry here to restore it.')};
const DIS={home:'HealthWiz is a wellness tracker, not a medical device. Health numbers are what you logged; nutrient values for menu foods are estimates. Quest progress, XP and attributes reflect logged habits only, never your health status.',food:'Calorie values come from the KOLEJ MARA KULIM Dewan Selera 2022 list. Protein, carbs, fat and fiber for these foods are estimates from the typical composition of each dish type (marked EST), not lab measurements. Items without a listed calorie value need your own number.',water:'Needs vary by person, climate and activity. More than your target is not better.',sleep:'The Dream Battle, Sleep Score and energy bar are game visualizations of your logged sleep, not medical measurements. Sleep goals follow AASM/CDC age recommendations.',pulse:'Pulse entries are measured and typed in by you. The waveform is only a heart-rate visualization, not an ECG. Chest pain, fainting or a worrying pulse: speak to a healthcare professional.',stair:'General exercise pacing aid, not medical treatment. Stop and get medical help for dizziness, chest pain, faintness or severe breathlessness.',stress:'A self check-in game. It does not diagnose anxiety, depression or any condition. The Wizard\'s Counsel is an AI listener, not therapy or a crisis service. In an emergency call 999; Befrienders KL 03-7627 2929.',bmi:'Adult BMI is a screening measure and does not describe every aspect of health.',calc:'Goals are estimates (Mifflin-St Jeor, AMDR, AASM/CDC), not medical prescriptions. Under 18? Ask a doctor or dietitian.',stats:'Statistics reflect only what you logged. Health connections show patterns in your own data, not causes.',guide:'General wellness suggestions based only on your logged entries. Concerning symptoms belong with a healthcare professional.',set:'Data is stored in this browser only. Download a backup regularly.'};
const pages={};
const svg=(w,h,b)=>'<svg viewBox="0 0 '+w+' '+h+'" shape-rendering="crispEdges" width="100%" height="100%">'+b+'</svg>';
const rc=(x,y,w,h,f,c)=>'<rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" fill="'+f+'"'+(c?' class="'+c+'"':'')+'/>';
const rs=a=>a.map(r=>rc(...r)).join('');
const fgl=(x,w,c)=>'<g class="fg">'+rs([[x,2,w,2,c],[x,4,w*.7|0,2,c],[x,6,w*.4|0,2,c]])+'</g>';
const TOWER=svg(40,90,rs([[8,30,24,60,'#3a2a4d'],[24,30,8,60,'#2a1d3a'],[6,22,28,8,'#2a1d3a'],[6,16,4,6,'#2a1d3a'],[13,16,4,6,'#2a1d3a'],[23,16,4,6,'#2a1d3a'],[30,16,4,6,'#2a1d3a'],[19,0,2,4,'#1c1228'],[18,4,4,4,'#1c1228'],[17,8,6,4,'#1c1228'],[16,12,8,4,'#1c1228'],[15,34,10,12,'#1c1228'],[16,35,8,10,'#ff3b2f','eye'],[19,37,2,6,'#1c1228'],[11,54,3,6,'#7a1f1f'],[26,54,3,6,'#7a1f1f'],[18,66,4,8,'#7a1f1f'],[8,80,24,2,'#2a1d3a']]));
const FENCE=svg(64,32,rs([[15,12,4,20,'#7a4c22'],[41,12,4,20,'#7a4c22'],[2,2,4,30,'#7a4c22'],[28,2,4,30,'#7a4c22'],[54,2,4,30,'#7a4c22'],[0,14,64,3,'#a8703a'],[0,22,64,3,'#a8703a'],[0,16,64,1,'#6a401c'],[0,24,64,1,'#6a401c']])+fgl(6,10,'#d9453d')+fgl(32,10,'#f2c14e')+fgl(58,6,'#2f8fd0'));
const PIPE=svg(32,40,rs([[0,0,32,12,'#0d3d14'],[1,1,30,10,'#3fbf4f'],[3,2,4,8,'#8ff08a'],[24,1,7,10,'#23903a'],[3,12,26,28,'#0d3d14'],[4,12,24,28,'#3fbf4f'],[7,12,4,28,'#8ff08a'],[22,12,5,28,'#23903a']]));
const COIN=svg(8,10,rs([[2,0,4,10,'#7a5a10'],[1,1,6,8,'#7a5a10'],[0,2,8,6,'#7a5a10'],[2,1,4,8,'#f2c14e'],[1,2,6,6,'#f2c14e'],[2,2,1,5,'#ffe9a0'],[5,3,1,5,'#c8962a'],[3,3,2,4,'#e0aa30']]));
const tw=x=>rs([[x,18,10,16,'#cfd6e4'],[x+6,18,4,16,'#aab4c8'],[x+4,8,2,2,'#2f8fd0'],[x+2,10,6,2,'#2f8fd0'],[x,12,10,2,'#2f8fd0'],[x-2,14,14,4,'#1f6ba3'],[x+3,24,4,6,'#2f8fd0'],[x+4,2,1,6,'#5b3a1e']])+fgl(x+5,6,'#f2c14e');
const isl=big=>svg(80,64,rs([[4,34,72,4,'#4caf50'],[4,34,72,2,'#7fd36b'],[6,38,68,6,'#8a5a2b'],[10,44,60,6,'#7a4c22'],[16,50,48,5,'#6a401c'],[24,55,32,4,'#5a3516'],[32,59,16,4,'#4a2c12']])+(big?rs([[28,14,24,20,'#cfd6e4'],[44,14,8,20,'#aab4c8'],[28,10,4,4,'#cfd6e4'],[34,10,4,4,'#cfd6e4'],[40,10,4,4,'#cfd6e4'],[46,10,4,4,'#aab4c8'],[37,24,6,10,'#5b3a1e'],[39,18,2,4,'#2f8fd0']])+tw(14)+tw(56):tw(35)));
pages.welcome=()=>{const bl=Array.from({length:96},(_,i)=>'<i style="left:'+(i/96*100).toFixed(1)+'%;height:'+(12+i*37%19)+'px;background:'+['#3a9a45','#4caf50','#6dcc5a','#2f8a3a'][i%4]+';animation-delay:'+(i*.06).toFixed(2)+'s"></i>').join(''),
cd=[[6,1.2,70,-10],[15,.8,95,-50],[26,1.5,120,-30],[10,.7,80,-65],[37,1,105,-90]].map(c=>'<div class="cd" style="top:'+c[0]+'%;--s:'+c[1]+';--d:'+c[2]+'s;animation-delay:'+c[3]+'s"></div>').join(''),
co=[[40,0,0],[50,26,-.4],[60,0,-.8]].map(c=>'<div class="cw" style="left:'+c[0]+'%;bottom:calc(22% + '+(118+c[1])+'px);--dl:'+c[2]+'s"><div class="cn">'+COIN+'</div></div>').join('');
return '<div class="wl"><div class="bg" aria-hidden="true"><div class="sky"></div>'+cd+'<div class="hl"></div><div class="tw">'+TOWER+'</div><div class="il big">'+isl(1)+'</div><div class="il sm">'+isl(0)+'</div><div class="gd"></div><div class="gr">'+bl+'</div><div class="fn">'+FENCE+'</div><div class="pp">'+PIPE+'</div><div class="hr"><div class="br2">'+HERO(5)+'</div></div>'+co+'</div><div class="tt"><div class="t1"><h1>HEALTHWIZ<br>KINGDOM</h1><p>a journey to better health</p></div><p class="by t2">BY GROUP 14</p></div><div class="ct"><button data-a="go" data-v="home">'+(st.e.length||st.xp?'CONTINUE QUEST':'START YOUR QUEST')+'</button></div><div class="ft">Wellness tracker, not a medical device.</div></div>'};
const REG=[['💧','Water Valley',()=>st.e.some(x=>x.c==='water'),'#7cc6f0','log water'],['🍗','Nutrition Village',()=>st.e.some(x=>x.c==='food'),'#f0c070','log a meal'],['❤️','Heartstone Hall',()=>st.e.some(x=>x.c==='pulse'||(x.c==='stair'&&x.m&&(+x.m.hrB||+x.m.hrA))),'#f09090','log heart rate in a workout'],['🧗','Stair Mountain',()=>st.e.some(x=>x.c==='stair'),'#c8b8a0','save a stair session'],['🧠','Mind Forest',()=>st.e.some(x=>x.c==='stress'),'#90d890','finish a stress check-in'],['⚖️','Balance Tower',()=>st.e.some(x=>x.c==='bmi')||st.s.set,'#c0a8f0','save BMI or a calorie target']];
const hdr=()=>{const L=lvl(),p=L.hi?(st.xp-L.lo)/(L.hi-L.lo)*100:100;return '<header>'+avatar(3)+'<div><h1>HEALTHWIZ</h1><small>Your Health. Your Quest.</small></div><div class="lv"><b>Lv '+(L.i+1)+' · '+L.n+'</b>'+bar(p,'var(--gold)')+'<small>'+st.xp+' XP'+(L.hi?' / '+L.hi:'')+'</small></div></header>'}; // v6 (§30): the three decorative hearts (and their "no hearts lost" note) are gone
function foodItems(){const q=S.q.trim().toLowerCase(),dd=DAYS[S.src];let ids,note='';if(q)ids=F.map((f,i)=>i).filter(i=>F[i][0].toLowerCase().includes(q));else if(dd&&dd[S.meal])ids=dd[S.meal];else{ids=F.map((f,i)=>i);if(S.src!=='all')note='<small>No '+MN(S.meal)+' in this menu day, showing all foods.</small>'}
return note+[...new Set(ids)].map(i=>'<button class="it" data-a="pick" data-i="'+i+'"><b>'+esc(F[i][0])+'</b><span>'+esc(F[i][1])+' · '+(F[i][2]==null?'kcal not listed':F[i][2]+' kcal')+'</span></button>').join('')}
// v6 (§31): the Nutrition section of the Nutrition & Hydration page (js/v6-provisions.js): the page title moved there, the
// calories and macros cards sit side by side, headings use pixel icons, and cards have ids that add-ons can anchor to.
pages.food=()=>{const d=today(),k=kc(d),T=st.s.kcal,R=rng(7),v=R.map(kc),dv=R.filter(x=>kc(x)>0),a7=dv.length?Math.round(avg(dv.map(kc))):0,hi=dv.length?dv.reduce((m,x)=>kc(x)>kc(m)?x:m):null,lo=dv.length?dv.reduce((m,x)=>kc(x)<kc(m)?x:m):null,f=S.sel!=null?F[S.sel]:null;
const so='<option value="all">All foods ('+F.length+')</option>'+Array.from({length:31},(_,i)=>'<option value="d'+(i+1)+'">Hari '+(i+1)+'</option>').join('')+Array.from({length:14},(_,i)=>'<option value="r'+(i+1)+'">'+(i+1)+' Ramadan</option>').join('');
return '<div class="nsg"><div class="card" id="fcal"><h3>'+HWPixel.icon('energy')+' CALORIES</h3><div class="row"><div><small>Calories consumed</small><div class="big">'+k+'<small> kcal</small></div></div><div><small>Daily target</small><div class="big">'+T+'<small> kcal</small></div></div><div><small>Remaining</small><div class="big">'+Math.max(0,T-k)+'<small> kcal</small></div></div></div>'+bar(k/T*100,k>T*1.1?'var(--vio)':'var(--grn)')+(k>T*1.1?'<small>Above your planned range by '+(k-T)+' kcal</small>':'')+'<div class="grid"><div class="t">7-day avg<b>'+a7+'<small> kcal</small></b></div><div class="t">Highest day<b>'+(hi?kc(hi):'–')+'</b><small>'+(hi||'')+'</small></div><div class="t">Lowest day<b>'+(lo?kc(lo):'–')+'</b><small>'+(lo||'')+'</small></div></div>'+chart(v,R,'var(--gold)','kcal',T)+'</div>'
+'<div class="nscol"><div class="card" id="fmac"><h3>'+HWPixel.icon('balance')+' MACRONUTRIENTS · TODAY</h3>'+macPanel(d,1)+'</div>'+(typeof HWScore!=='undefined'?HWScore.fvCard():'')+'</div></div>'+
'<div class="card" id="fpick"><h3>'+HWPixel.icon('food')+' PICK A FOOD</h3><div class="row">'+MEALS.map(m=>'<button class="chip '+(S.meal===m[0]?'on':'')+'" data-a="meal" data-m="'+m[0]+'">'+m[1]+'</button>').join('')+'</div>'+HWWhen.html({id:'food',cats:['food']})+'<label>Menu day<select data-ch="src">'+so.replace('value="'+S.src+'"','value="'+S.src+'" selected')+'</select></label><label>Search all foods<input id="q" data-in="q" value="'+esc(S.q)+'" placeholder="e.g. nasi, ayam, susu"></label><button data-a="cf" style="width:100%;margin:8px 0">+ ADD MORE FOOD</button>'+
(S.cf?'<div class="card"><h3>CUSTOM FOOD</h3><label>Food name<input id="cn"></label><label>Serving size<input id="cs" placeholder="e.g. 1 plate / 150 g"></label><label>Calories (kcal)<input id="cc" type="number" min="0" max="5000" inputmode="decimal"></label><label>Meal<select id="cm">'+MEALS.map(m=>'<option value="'+m[0]+'"'+(m[0]===S.meal?' selected':'')+'>'+m[1]+'</option>').join('')+'</select></label><div class="row"><label>Protein (g)<input id="cp" type="number" min="0" max="500" step="0.1" inputmode="decimal"></label><label>Carbs (g)<input id="cb" type="number" min="0" max="1000" step="0.1" inputmode="decimal"></label></div><div class="row"><label>Fat (g)<input id="cfa" type="number" min="0" max="500" step="0.1" inputmode="decimal"></label><label>Fiber (g)<input id="cfb" type="number" min="0" max="200" step="0.1" inputmode="decimal"></label></div><small class="mut">Macros are optional and for the whole serving (check the nutrition label). Leave blank if unknown.</small><button data-a="savecf" style="margin-top:8px;width:100%">SAVE CUSTOM FOOD</button></div>':'')+
(f?'<div class="card" id="det"><h3>'+esc(f[0])+'</h3><p>Standard serving: <b>'+esc(f[1])+'</b> · '+(f[2]==null?'<b>kcal not listed in KOLEJ MARA KULIM data</b>':'<b class="num">'+f[2]+' kcal</b>')+'</p>'+(f[2]==null?'<label>Your kcal per standard serving<input id="ck" data-in="ck" type="number" min="0" max="3000" inputmode="decimal" value="'+esc(S.ck)+'"></label>':'')
+'<label>Servings</label><div class="row"><button class="g" data-a="qm" aria-label="Fewer servings">−</button><span class="big" style="text-align:center">'+S.qty+'</span><button class="g" data-a="qp" aria-label="More servings">+</button></div>'
+'<label>Portion size <small class="mut">(each serving compared with the standard)</small></label><div class="pm" role="group" aria-label="Portion size">'+PMS.map(m=>'<button class="chip'+(S.pm===m?' on':'')+'" data-a="pm" data-m="'+m+'" aria-pressed="'+(S.pm===m)+'">'+m+'×</button>').join('')+'</div>'
+'<div id="fprev">'+fprev()+'</div><button data-a="addfood" style="width:100%;margin-top:10px">ADD TO LOG</button></div>':'')+'<div id="fl">'+foodItems()+'</div></div><div class="card" id="flog"><h3>'+HWPixel.icon('scroll')+' TODAY\'S FOOD LOG</h3>'+list('food')+'</div>'
+'<div class="card" id="fwk"><h3>'+HWPixel.icon('chart')+' 7-DAY NUTRITION LOG '+HWHelp.btn('nutest')+'</h3>'+macTable()+'</div>'};
pages.water=()=>{const d=today(),w=wt(d),t=st.s.water,p=Math.min(100,w/t*100),lv=Math.min(1,w/t),R=rng(7),wd=wdays(),rem=Math.max(0,t-w),G=S.wg=S.wg||'w',wx=st.e.filter(x=>x.c==='water').length*5;
const stage=wd>=21?5:wd>=14?4:wd>=9?3:wd>=5?2:wd>=2?1:0;
const STG=[['🕳️','Old Well','The stones are dry and cracked. Log water to begin restoring it.'],['🌱','First Sprouts','Small plants gather near the well.'],['🌳','Green Trees','Trees have taken root around the square.'],['✨','Fireflies','Fireflies dance over the water at dusk.'],['🦌','Animals Return','Deer and rabbits drink at the well again.'],['🌸','Village Restored','Flowers bloom everywhere. The village thrives!']];
const kp=[],wk=R.filter(x=>wt(x)>0);
if(wk.length>=3)kp.push('Your hydration has been fairly consistent this week ('+Math.round(avg(wk.map(wt)))+' mL/day on logged days).');
if(w===0)kp.push('You have not logged any water today yet.');
else if(w<t*.5)kp.push('You have not logged much water today so far.');
const hrs=A('water').map(e=>+e.t.slice(0,2));
if(hrs.length>=2&&avg(hrs)>=15)kp.push('Most of your intake happens later in the day.');
else if(hrs.length>=2&&avg(hrs)<12)kp.push('Most of your intake happens earlier in the day — nice pacing.');
kp.push('Needs vary by person, climate and activity. For medical circumstances, follow the guidance of a healthcare professional.');
let gh;
if(G==='d'){const hh=Array(24).fill(0);A('water').forEach(e=>hh[+e.t.slice(0,2)]+= +e.v||0);gh=chart(hh,Array.from({length:24},(_,i)=>i+':00'),'var(--blue)','mL')}
else if(G==='w'){gh=chart(R.map(wt),R.map(x=>['SUN','MON','TUE','WED','THU','FRI','SAT'][new Date(x+'T12:00:00').getDay()]),'var(--blue)','mL')}
else{const R30=rng(30);gh=chart(R30.map(wt),R30.map(x=>x.slice(5)),'var(--blue)','mL')}
const ACH=[['💧','First Drop','Log your first water entry',cnt('water')>=1],['🪣','Bucket Carrier','Track water on 3 days',wd>=3],['🛡️','Well Keeper','Track water on 7 days',wd>=7],['🏘️','Village Restored','Track water on 21 days',wd>=21]];
const wrem=st.s.wrem||0;
// v6 (§31): the Hydration section of the Nutrition & Hydration page: its title and line moved to the section header there
// (js/v6-provisions.js), headings use pixel icons, WORLD PROGRESSION has an id for anchors. The Water Quest is unchanged.
return '<div class="card"><div class="row" style="align-items:baseline"><b class="big">'+w+' / '+t+' mL</b><span class="mut">'+p.toFixed(0)+'%</span></div>'+bar(p,'var(--blue)')+'</div>'
+'<div class="wq" id="wq"><div class="path"></div>'
+'<svg class="wqp" viewBox="0 0 90 60" aria-hidden="true"><ellipse cx="45" cy="34" rx="42" ry="24" fill="#1c5e96"/><ellipse cx="45" cy="31" rx="37" ry="20" fill="#2f8fd0"/><path class="wv1" d="M8 30 q7 -6 14 0 t14 0 t14 0 t14 0 t14 0 t14 0" stroke="#8fd4ff" stroke-width="3" fill="none"/><ellipse class="wqspk" cx="30" cy="26" rx="3" ry="2" fill="#dff4ff"/><ellipse class="wqspk" style="animation-delay:.7s" cx="58" cy="34" rx="3" ry="2" fill="#dff4ff"/></svg>'
+'<svg class="wqwell" viewBox="0 0 200 200"><circle cx="100" cy="100" r="97" fill="#cfc4a5"/><circle cx="100" cy="100" r="92" fill="none" stroke="#a99e82" stroke-width="9" stroke-dasharray="13 7"/><circle cx="100" cy="100" r="80" fill="#7d7462"/><circle cx="100" cy="100" r="72" fill="none" stroke="#5f5747" stroke-width="7" stroke-dasharray="11 9"/><circle cx="100" cy="100" r="63" fill="#16222e"/>'
+'<g class="wtr" id="wqwtr" style="transform:scale('+(0.25+0.75*lv).toFixed(3)+')"><circle cx="100" cy="100" r="58" fill="#1c5e96"/><circle cx="100" cy="100" r="46" fill="#2f8fd0"/><path class="wv1" d="M56 100 q11 -9 22 0 t22 0 t22 0 t22 0" stroke="#8fd4ff" stroke-width="5" fill="none"/><circle class="wqspk" cx="84" cy="86" r="4" fill="#bfe6ff"/><circle class="wqspk" style="animation-delay:.6s" cx="118" cy="108" r="3" fill="#dff4ff"/><circle class="wqspk" style="animation-delay:1.1s" cx="100" cy="122" r="2.5" fill="#bfe6ff"/></g>'
+'<text x="100" y="196" text-anchor="middle" style="font:14px monospace" fill="#2b2418">'+Math.round(p)+'%</text></svg>'
+'<div class="wqd"><i style="height:'+p+'%"></i></div>'
+'<div class="wqch" id="wqch"><div class="wqbk"></div>'+HERO(3)+'</div><div class="wqpr" id="wqpr"><i></i></div></div>'
+'<div class="card"><h3>'+HWPixel.icon('water')+' ADD WATER</h3>'+HWWhen.html({id:'water',cats:['water']})+'<div class="row"><button data-a="wa" data-v="100">+100 mL</button><button data-a="wa" data-v="250">+250 mL</button><button data-a="wa" data-v="500">+500 mL</button><button data-a="wa" data-v="750">+750 mL</button></div><div class="row" style="margin-top:10px"><input id="wc" type="number" min="1" max="1500" placeholder="Custom mL"><button data-a="wcu">ADD WATER</button></div>'+(w>=t?'<p>Target reached. There is no need to drink more today.</p>':'<p class="mut">'+rem+' mL to go. Sip steadily through the day.</p>')+'</div>'
+'<div class="grid"><div class="t">💧 Water Collected<b>'+w+' mL</b></div><div class="t">🎯 Daily Target<b>'+t+' mL</b></div><div class="t">📊 Progress<b>'+p.toFixed(0)+'%</b></div><div class="t">🥤 Remaining<b>'+rem+' mL</b></div><div class="t">⭐ Hydration XP<b>'+wx+' XP</b></div></div>'
+'<div class="card" style="margin-top:14px"><h3>'+HWPixel.icon('scroll')+' WATER HISTORY</h3>'+list('water')+'<p><b>TOTAL: '+w+' mL</b></p></div>'
+'<div class="card"><h3>'+HWPixel.icon('chart')+' HYDRATION GRAPH</h3><div class="row">'+[['d','DAY'],['w','WEEK'],['m','MONTH']].map(g=>'<button class="chip '+(G===g[0]?'on':'')+'" data-a="wgr" data-g="'+g[0]+'">'+g[1]+'</button>').join('')+'</div>'+gh+'</div>'
+'<div class="card" id="wworld"><h3>'+HWPixel.icon('map')+' WORLD PROGRESSION</h3><div class="row" style="align-items:center"><span style="font-size:30px">'+STG[stage][0]+'</span><div><b>'+STG[stage][1]+'</b><br><small>'+STG[stage][2]+'</small></div></div>'+bar(Math.min(100,wd/21*100),'var(--grn)')+'<small>The village grows with consistent tracking days ('+wd+' so far), never with excessive intake in one day.</small></div>'
+'<div class="card"><h3>'+HWPixel.icon('wizard')+' WELL KEEPER</h3>'+kp.map(x=>'<p>• '+x+'</p>').join('')+'</div>'
+'<div class="card"><h3>'+HWPixel.icon('achievement')+' ACHIEVEMENTS</h3><div class="grid">'+ACH.map(a=>'<div class="t bd '+(a[3]?'':'lock')+'"><span class="bi">'+(a[3]?a[0]:'🔒')+'</span><b>'+a[1]+'</b><small>'+a[2]+'</small></div>').join('')+'</div></div>'
+'<div class="card"><h3>'+HWPixel.icon('bell')+' REMINDERS</h3><div class="row"><label>Remind me<select id="wre">'+[[0,'Off'],[60,'Every 1 hour'],[120,'Every 2 hours'],['c','Custom']].map(o=>'<option value="'+o[0]+'"'+(wrem===o[0]||(o[0]==='c'&&wrem&&wrem!==60&&wrem!==120)?' selected':'')+'>'+o[1]+'</option>').join('')+'</select></label><label>Custom (minutes)<input id="wrec" type="number" min="5" max="720" value="'+(wrem&&wrem!==60&&wrem!==120?wrem:90)+'"></label></div><button data-a="wrems">SAVE REMINDER</button><p class="mut">💧 THE WELL NEEDS YOU! — gentle in-app reminder, never spammy.</p></div>'};
function fillFX(a,b){const o=document.createElement('div'),p=Math.min(100,Math.max(8,b/st.s.water*100));o.className='fx';o.innerHTML='<div class="fw"><div class="wv"></div>'+(p>45?'<div class="sw">'+HERO(4)+'</div>':'')+'</div>';for(let i=0;i<8+Math.round(p/6);i++){const u=document.createElement('u'),z=6+Math.random()*12|0;u.style.cssText='left:'+Math.random()*96+'%;width:'+z+'px;height:'+z+'px;animation-delay:'+Math.random()*2+'s';o.appendChild(u)}document.body.appendChild(o);requestAnimationFrame(()=>requestAnimationFrame(()=>o.firstChild.style.height=p+'%'));const c=$('#cnt'),t0=performance.now();if(c)(function f(t){const k=Math.min(1,(t-t0)/1600);c.textContent=Math.round(a+(b-a)*k);if(k<1)requestAnimationFrame(f)})(t0);[300,400,500,650].forEach((f,i)=>setTimeout(()=>sfx(f,.08),i*250));setTimeout(()=>o.classList.add('out'),3200);setTimeout(()=>o.remove(),4100)}
function complete(){const o=document.createElement('div');o.className='fx done';o.dataset.a='dclose';let h='<div>HYDRATION<br>QUEST<br>COMPLETE!<br><small style="font-size:9px">tap to continue</small></div>';for(let i=0;i<40;i++)h+='<u style="left:'+Math.random()*98+'%;width:10px;height:10px;background:'+['#f2c14e','#2f8fd0','#5cc05a','#e0483f'][i%4]+';animation-delay:'+Math.random()*2+'s"></u>';o.innerHTML=h;document.body.appendChild(o);[523,659,784,1047].forEach((f,i)=>setTimeout(()=>sfx(f,.15),i*150));gain(50,'Hydration quest!');setTimeout(()=>o.remove(),6000)}
function drink(v){if(!(v>=1&&v<=1500)){toast('Enter between 1 and 1500 ml');return}const bw=HWWhen.stamp({sig:'w'+v});if(!bw)return;if(bw.back&&bw.d!==today()){add('water',v,{},'',bw.d,bw.t,5,'Water');HWWhen.saved(bw,'Water');render();return}const o=wt(),t=st.s.water;add('water',v,{},'',bw.d,bw.t,5,'Water');const n=wt();if(S.v==='water'&&$('#wqch'))wqFlow(v,o,n);else{render();fillFX(o,n)}if(o<t&&n>=t)setTimeout(complete,4200);else if(n>t*1.5)toast('You are well past your target. No need to drink more today.');wqRemind()}
function wdays(){return new Set(st.e.filter(x=>x.c==='water').map(x=>x.d)).size}
function sdays(){return new Set(st.e.filter(x=>x.c==='sleep').map(x=>x.d)).size}
function tmin(s){if(!s)return null;const a=(''+s).split(':');return +a[0]*60+(+a[1]||0)}
function nrm(m){return m<720?m+1440:m}
function bstd(a){if(a.length<2)return 0;const m=avg(a);return Math.sqrt(avg(a.map(x=>(x-m)*(x-m))))}
function fmtm(m){m=((Math.round(m)%1440)+1440)%1440;return ('0'+Math.floor(m/60)).slice(-2)+':'+('0'+m%60).slice(-2)}
function wqFlow(v,prev,now){const ch=$('#wqch');if(!ch){render();return}const lv=$('#wqwtr'),pr=$('#wqpr');
ch.classList.add('walk');ch.style.left='16%';ch.style.top='60%';
setTimeout(()=>{ch.classList.remove('walk');ch.classList.add('carry');sfx(500,.08);splashAt('16%','62%')},950);
setTimeout(()=>{ch.classList.add('walk');ch.style.left='68%';ch.style.top='48%'},1400);
setTimeout(()=>{ch.classList.remove('walk');if(pr)pr.style.display='block';sfx(300,.15);
setTimeout(()=>{if(pr)pr.style.display='none';ch.classList.remove('carry');ch.classList.add('cel');if(lv)lv.style.transform='scale('+(0.25+0.75*Math.min(1,now/st.s.water))+')';const gd=$('.wqd i');if(gd)gd.style.height=Math.min(100,now/st.s.water*100)+'%';splashAt('68%','40%');flText('✨ +'+v+' mL',0);flText('⭐ +5 XP',1);sfx(784,.12);
setTimeout(()=>{ch.classList.remove('cel');ch.style.left='16%';ch.style.top='52%';flood2(v);setTimeout(render,3600)},1200)},700)},2400)}
function splashAt(l,t){const w=$('#wq');if(!w)return;for(let i=0;i<3;i++){const s=document.createElement('i');s.className='wqsp go';s.style.cssText='left:'+l+';top:'+t+';animation-delay:'+(i*.12)+'s';w.appendChild(s);setTimeout(()=>s.remove(),1300)}}
function flText(t,k){const w=$('#wq');if(!w)return;const f=document.createElement('div');f.className='wqfl';f.style.cssText='left:'+(34+k*20)+'%;top:'+(26+k*16)+'%';f.textContent=t;w.appendChild(f);setTimeout(()=>f.remove(),1700)}
function flood2(v){const o=document.createElement('div');o.className='fl2';o.innerHTML='<div class="ly a"></div><div class="ly b"></div><div class="ly c"></div><div class="msg">💧 +'+v+' mL<br>HYDRATION RESTORED!</div>';
for(let i=0;i<26;i++){const u=document.createElement('u'),z=4+Math.random()*10|0;u.style.cssText='left:'+Math.random()*98+'%;width:'+z+'px;height:'+z+'px;animation-delay:'+Math.random()*2+'s';o.appendChild(u)}
for(let i=0;i<4;i++){const f=document.createElement('i');f.className='flf';f.style.cssText='top:'+(55+Math.random()*35)+'%;--t:'+(5+Math.random()*4)+'s;animation-delay:-'+Math.random()*5+'s';o.appendChild(f)}
document.body.appendChild(o);requestAnimationFrame(()=>requestAnimationFrame(()=>{o.querySelectorAll('.ly').forEach((l,i)=>l.style.height=(70+i*10)+'%');o.querySelector('.msg').style.opacity=1}));
[300,420,540,700].forEach((f,i)=>setTimeout(()=>sfx(f,.08),i*180));
setTimeout(()=>{o.querySelectorAll('.ly').forEach(l=>l.style.height='0');o.querySelector('.msg').style.opacity=0},2600);
setTimeout(()=>o.remove(),4400)}
function wqRemind(){clearTimeout(S.wrT);const m=st.s.wrem||0;if(!m)return;S.wrT=setTimeout(()=>{toast('💧 THE WELL NEEDS YOU! Time for a hydration check? <button class="sm" data-a="go" data-v="water">LOG WATER</button>');wqRemind()},m*60000)}
acts.wgr=d=>{S.wg=d.g;render()};
acts.wrems=()=>{const v=$('#wre').value;st.s.wrem=v==='c'?Math.max(5,Math.min(720,+$('#wrec').value||120)):+v;save();wqRemind();toast('Reminder saved');render()};
function slpDur(b,w){const x=tmin(b),y=tmin(w);if(x==null||y==null)return 0;let d=y-x;if(d<=0)d+=1440;return Math.round(d/6)/10}
function slpScore(h,aw,lat,rest){const a=st.p.age,[lo,hi]=SR(+a||16);let dp;if(h>=lo&&h<=hi)dp=40;else{const df=h<lo?lo-h:h-hi;dp=Math.max(0,Math.round(40-df/3*40))}const ap=[20,14,8,4][Math.min(3,aw|0)],lp=lat<=15?15:lat<=30?11:lat<=45?7:4,rp=Math.round((rest||3)/5*15);const bm=LC('sleep').slice(-7).map(e=>tmin(e.m.bed)).filter(x=>x!=null).map(nrm),sd=bstd(bm),cp=bm.length<3?5:sd<=30?10:sd<=60?6:3;return Math.min(100,dp+ap+lp+rp+cp)}
function slInit(){const b=$('#slb'),w=$('#slw');if(!b||!w)return;const f=()=>{const v=slpDur(b.value,w.value);if(v)$('#sld').value=(''+v).replace(/\.0+$/,'')};b.addEventListener('input',f);w.addEventListener('input',f)}
acts.slaw=d=>{S.slaw=+d.i;render()};
acts.slrest=d=>{S.slrest=+d.i;render()};
acts.slchk=d=>{st.ck=st.ck||{};const k=today(),a=st.ck[k]=st.ck[k]||[0,0,0,0,0];a[+d.i]=a[+d.i]?0:1;save();render()};
acts.sldq=()=>{S.dq={n:0};render()};
acts.slstar=(d,t)=>{if(!S.dq||S.dq.done)return;t.style.display='none';S.dq.n++;sfx(600+S.dq.n*80,.08);const c=$('#dqn');if(c)c.textContent=S.dq.n+'/5';if(S.dq.n>=5){S.dq.done=1;st.dqn=(st.dqn||0)+1;gain(10,'Dream Quest');toast('✨ DREAM QUEST COMPLETE');setTimeout(render,700)}};
acts.slsave=()=>{const b=$('#slb').value,w=$('#slw').value;let h=+$('#sld').value||slpDur(b,w);if(!(h>0&&h<=20)){toast('Check your sleep duration');return}const aw=S.slaw==null?0:S.slaw,lat=+$('#sll').value||0,rest=S.slrest||3,sd=HWWhen.stamp({time:false,fb:w});if(!sd)return;const d=sd.d,sc=slpScore(h,aw,lat,rest);if(sd.back){const k=d+b+w,n=Date.now();if(A('sleep',d).length&&!(S.sldup&&S.sldup.k===k&&n-S.sldup.at>1200)){if(!(S.sldup&&S.sldup.k===k))S.sldup={k,at:n};toast('Sleep is already logged for '+HWWhen.label(d)+'. Tap LOG SLEEP again to add another.');return}S.sldup=null}add('sleep',h,{bed:b,wake:w,aw,lat,rest,score:sc},'',d,sd.t,15,'Sleep logged');HWWhen.saved(sd,'Sleep');S.slaw=null;S.slrest=null;render()};
pages.sleep=()=>{const L=LC('sleep'),last=L.slice(-1)[0],a=st.p.age,RG=SR(+a||16),R=rng(7),L7=L.filter(e=>R.indexOf(e.d)>=0),sc=last?last.m.score||0:0,dur=last?last.v:0;
const bm=L7.map(e=>tmin(e.m.bed)).filter(x=>x!=null).map(nrm),wm=L7.map(e=>tmin(e.m.wake)).filter(x=>x!=null),sd=bstd(bm),wk7=L7.length;
const inR=dur>=RG[0]&&dur<=RG[1];
const stars=Array.from({length:26},(_,i)=>'<i class="st1" style="left:'+(i*37%96)+'%;top:'+(i*23%52)+'%;--d:'+(1.4+i%5*.5)+'s;--l:'+(i*.3%2)+'s"></i>').join('');
const flies=Array.from({length:7},(_,i)=>'<i class="qf" style="left:'+(8+i*13)+'%;bottom:'+(10+i*7%26)+'%;animation-delay:'+(i*.4)+'s"></i>').join('');
const adv=[];
if(wk7>=2){const ds=L7.map(e=>+e.v);adv.push('Average sleep this week: '+avg(ds).toFixed(1)+'h (range '+Math.min.apply(0,ds)+'–'+Math.max.apply(0,ds)+'h).');
adv.push(sd<=30?'Your sleep schedule has been fairly consistent this week (bedtime ±'+Math.round(sd)+' min).':'Your bedtime has varied considerably this week (±'+Math.round(sd)+' min).');
const awa=avg(L7.map(e=>e.m.aw||0)),rf=avg(L7.map(e=>e.m.rest||3));
adv.push('Average awakenings: '+awa.toFixed(1)+' per night · average morning restfulness: '+rf.toFixed(1)+'/5.');
if(awa>=2)adv.push('Frequent awakenings that regularly affect you are worth discussing with a healthcare professional.');
const sh=L7.filter(e=>str(e.d)!=null&&e.v<6.5),lg=L7.filter(e=>str(e.d)!=null&&e.v>=7.5);
if(sh.length&&lg.length){const s1=avg(sh.map(e=>str(e.d))),s2=avg(lg.map(e=>str(e.d)));if(s1>s2)adv.push('You reported higher stress on days following shorter nights ('+s1.toFixed(1)+' vs '+s2.toFixed(1)+' /10). An observed pattern, not proof of causation.')}}
else adv.push('Log a few nights of sleep and the Dream Advisor will share observations here.');
adv.push('Game observations only — never medical conclusions from a single night.');
const CKL=['Reduce heavy screen use near bedtime','Comfortable, dark room','Avoid caffeine late in the day','Consistent bedtime when possible','Allow enough time for sleep'],ck=(st.ck||{})[today()]||[];
const SA=[['🌙','First Dream','Log your first night',cnt('sleep')>=1],['✨','Dream Explorer','Log sleep on 7 days',sdays()>=7],['⛺','Night Camp','Fairly consistent week',sd<=30&&wk7>=5],['🌟','Restored','Log sleep all 7 days this week',wk7>=7]];
const dq=sheepCard();
const wkRows=L7.length?L7.map(e=>'<div class="er"><span>'+e.d.slice(5)+'</span><span>🛏 '+esc(e.m.bed||'--')+' → ☀ '+esc(e.m.wake||'--')+' · '+(e.m.aw||0)+' awakenings</span><b>'+e.v+' h</b></div>').join(''):'<p class="mut">No entries this week yet.</p>';
return '<h2>🌙 DREAM QUEST</h2><p class="mut">Rest your character. Restore your energy.</p>'
+'<div class="card" id="dbatc"><h3>⚔️ DREAM BATTLE '+HWHelp.btn('sleepgame')+'</h3>'+dbat()+'</div>'
+'<div class="card"><h3>🛏️ LAST NIGHT</h3><div class="grid"><div class="t">🌙 Sleep Duration<b>'+(dur?dur+' h':'–')+'</b></div><div class="t">🛏 Bedtime<b>'+(last?esc(last.m.bed||'--'):'–')+'</b></div><div class="t">☀ Wake<b>'+(last?esc(last.m.wake||'--'):'–')+'</b></div><div class="t">🌙 Awakenings<b>'+(last?last.m.aw||0:'–')+'</b></div></div></div>'
+'<div class="card"><h3>😴 DREAM SCORE (game visual) '+HWHelp.btn('sleepscore')+'</h3><div class="big">'+sc+' / 100</div>'+bar(sc,'var(--vio)')+'</div>'
+'<div class="card"><h3>⚡ ENERGY RESTORED '+HWHelp.btn('sleepgame')+'</h3>'+bar(sc,'var(--gold)')+'</div>'
+'<div class="card"><h3>🌙 SLEEP DURATION '+HWHelp.btn('sleeprange','Recommended sleep range','<p>Recommended range for your age: <b>'+RG[0]+'–'+RG[1]+' h</b>. A range, not an exact requirement.</p><p>Sleep goals follow AASM/CDC age recommendations.</p>')+'</h3><div class="big">'+(dur?dur+' h':'–')+'</div>'+bar(Math.min(100,dur/RG[1]*100),'var(--blue)')+'<small>'+(last?(inR?'Last night was within your '+RG[0]+'–'+RG[1]+' h range. ✓':'Last night was outside your '+RG[0]+'–'+RG[1]+' h range.'):'Your range: '+RG[0]+'–'+RG[1]+' h.')+'</small></div>'
+'<div class="card"><h3>😌 MORNING RESTFULNESS</h3><div class="row">'+[['😫','Not rested'],['😕','Slightly rested'],['😐','Okay'],['🙂','Rested'],['😄','Very rested']].map((r,i)=>'<button class="chip '+((S.slrest||3)===i+1?'on':'')+'" data-a="slrest" data-i="'+(i+1)+'">'+r[0]+'<br>'+r[1]+'</button>').join('')+'</div><small>Used in your Sleep Score.</small></div>'
+'<div class="card"><h3>🛏️ LOG SLEEP</h3><div class="row"><label>Bedtime<input id="slb" type="time" value="'+(last?esc(last.m.bed||'23:00'):'23:00')+'"></label><label>Wake-up time<input id="slw" type="time" value="'+(last?esc(last.m.wake||'07:00'):'07:00')+'"></label></div><div class="row"><label>Total sleep (hours, auto)<input id="sld" type="number" min="0" max="20" step="0.25"></label><label>Minutes to fall asleep<input id="sll" type="number" min="0" max="300" value="15"></label></div><label>Night awakenings</label><div class="row">'+[0,1,2,3].map(i=>'<button class="chip '+((S.slaw==null?0:S.slaw)===i?'on':'')+'" data-a="slaw" data-i="'+i+'">'+(i===3?'3+':i)+'</button>').join('')+'</div>'+HWWhen.html({id:'sleep',time:false,cats:['sleep'],label:'Woke up on…',hint:'Sleep is filed under the day you woke up, so a night that crosses midnight counts for the morning you woke.'})+'<button data-a="slsave">+ LOG SLEEP</button></div>'
+'<div class="card"><h3>📅 SLEEP CONSISTENCY (7 DAYS)</h3>'+wkRows+chart(R.map(x=>{const e=L.filter(y=>y.d===x).pop();return e?e.v:null}),R.map(x=>['SUN','MON','TUE','WED','THU','FRI','SAT'][new Date(x+'T12:00:00').getDay()]),'var(--vio)','h')+'<p>'+(wk7>=2?(sd<=30?'Your sleep schedule has been fairly consistent this week.':'Your bedtime has varied considerably this week.'):'Log sleep to see consistency.')+'</p></div>'
+'<div class="card"><h3>📊 WEEKLY STATS</h3>'+(wk7?'<div class="grid"><div class="t">🌙 Avg sleep<b>'+avg(L7.map(e=>+e.v)).toFixed(1)+' h</b></div><div class="t">🛏 Avg bedtime<b>'+(bm.length?fmtm(avg(bm)>1440?avg(bm)-1440:avg(bm)):'–')+'</b></div><div class="t">☀ Avg wake<b>'+(wm.length?fmtm(avg(wm)):'–')+'</b></div><div class="t">😌 Avg restfulness<b>'+avg(L7.map(e=>e.m.rest||3)).toFixed(1)+'/5</b></div><div class="t">🌙 Avg awakenings<b>'+avg(L7.map(e=>e.m.aw||0)).toFixed(1)+'</b></div><div class="t">📅 Consistency<b>±'+Math.round(sd)+' min</b></div></div>':'<p class="mut">No entries this week yet.</p>')+'</div>'
+'<div class="card"><h3>🧙 DREAM ADVISOR</h3>'+adv.map(x=>'<p>• '+x+'</p>').join('')+'</div>'
+'<div class="card" id="sheepc"><h3>🐑 DREAM QUEST: COUNTING SHEEP</h3>'+dq+'</div>'
+'<div class="card"><h3>🌙 BEFORE BED CHECKLIST</h3>'+CKL.map((c,i)=>'<div class="ckl" data-a="slchk" data-i="'+i+'"><span>'+(ck[i]?'☑':'☐')+'</span><span>'+c+'</span></div>').join('')+'<small class="mut">Resets each day.</small></div>'
+'<div class="card"><h3>🏆 ACHIEVEMENTS</h3><div class="grid">'+SA.map(x=>'<div class="t bd '+(x[3]?'':'lock')+'"><span class="bi">'+(x[3]?x[0]:'🔒')+'</span><b>'+x[1]+'</b><small>'+x[2]+'</small></div>').join('')+'</div></div>'
+'<div class="card"><h3>📜 SLEEP HISTORY</h3>'+list('sleep')+'</div>'};
acts.wa=d=>drink(+d.v);acts.wcu=()=>drink(+$('#wc').value);acts.dclose=(d,t)=>t.remove();
pages.pulse=()=>{const ps=LC('pulse'),l=ps.slice(-1)[0];return '<h2>❤️ MEASURE PULSE</h2><div class="card"><ol><li>Find your pulse manually (wrist or neck).</li><li>Count beats for 15 s (x4), 30 s (x2) or 60 s.</li><li>Enter the result below.</li><li>Save it.</li></ol><div class="row"><label>BPM<input id="pb" type="number" min="30" max="220"></label><label>Activity<select id="ps">'+['Resting','After walking','After stairs','After exercise','Other'].map(x=>'<option>'+x+'</option>').join('')+'</select></label></div><div class="row"><label>Date<input id="pd" type="date" value="'+today()+'"></label><label>Time<input id="pt" type="time" value="'+nowT()+'"></label></div><label>Notes<input id="pn"></label><button data-a="savepulse">SAVE PULSE</button></div><div class="card"><h3>HEART RATE VISUALIZATION</h3><canvas id="ecg" width="600" height="190" style="width:100%;height:190px;display:block;border:3px solid var(--ln);background:#04120a"></canvas><small>'+(l?'Traced at your latest logged pulse ('+l.v+' BPM): higher BPM = beats closer together.':'Log a pulse to animate this.')+' Not a medical ECG.</small></div><div class="card"><h3>HISTORY (Time | Activity | BPM)</h3>'+(ps.length?ps.slice(-12).reverse().map(e=>row(e,1)).join(''):'<p class="mut">No pulse entries yet.</p>')+'</div>'};
function ecg(){const c=$('#ecg');if(!c)return;const x=c.getContext('2d'),L=LC('pulse').slice(-1)[0],bpm=L?+L.v:0,RR=bpm?60/bpm:0,SPD=120,t0=performance.now();
const gs=(d,m,w,a)=>a*Math.exp(-(d-m)*(d-m)/(2*w*w));
const sig=t=>{if(!RR)return 0;const q=Math.sqrt(RR),k0=Math.round(t/RR);let y=.014*Math.sin(t*1.6);for(let k=k0-2;k<=k0+2;k++){const d=t-k*RR;y+=gs(d,-.17,.024,.13)+gs(d,-.03,.009,-.11)+gs(d,0,.011,1)+gs(d,.031,.011,-.24)+gs(d,.1+.16*q,.034+.016*q,.3*Math.min(1,.55+.45*q))}return y};
(function f(now){if($('#ecg')!==c)return;const dpr=Math.min(3,window.devicePixelRatio||1),W=c.clientWidth,H=c.clientHeight;if(c.width!==Math.round(W*dpr)||c.height!==Math.round(H*dpr)){c.width=Math.round(W*dpr);c.height=Math.round(H*dpr)}
x.setTransform(dpr,0,0,dpr,0,0);x.fillStyle='#04120a';x.fillRect(0,0,W,H);
for(let g=0;g<=W;g+=12){x.fillStyle=g%60?'rgba(63,208,90,.09)':'rgba(63,208,90,.24)';x.fillRect(g,0,1,H)}for(let g=0;g<=H;g+=12){x.fillStyle=g%60?'rgba(63,208,90,.09)':'rgba(63,208,90,.24)';x.fillRect(0,g,W,1)}
const cyc=W/SPD,T=(now-t0)/1000,n=Math.floor(T/cyc),cx=(T-n*cyc)*SPD,yy=t=>H*.68-sig(t)*H*.56;
x.lineWidth=2;x.lineJoin='miter';x.miterLimit=12;x.lineCap='butt';x.strokeStyle='#4dff7c';x.shadowColor='rgba(77,255,124,.65)';x.shadowBlur=4;
const seg=(a,b,base)=>{x.beginPath();for(let p=a;p<=b;p+=.5){const y=yy(base+p/SPD);p===a?x.moveTo(p,y):x.lineTo(p,y)}x.stroke()};
seg(0,cx,n*cyc);if(cx+28<W)seg(cx+28,W,(n-1)*cyc);
x.shadowBlur=0;x.fillStyle='#eaffee';x.beginPath();x.arc(cx,yy(T),2.5,0,7);x.fill();
x.fillStyle='#7dffa0';x.font='bold 12px ui-monospace,Menlo,Consolas,monospace';x.fillText(L?bpm+' BPM · '+L.m.st:'NO PULSE LOGGED',8,16);
requestAnimationFrame(f)})(t0)}
acts.savepulse=()=>{const v=+$('#pb').value;if(!(v>=30&&v<=220)){toast('Check your value: enter 30 to 220 BPM');return}add('pulse',v,{st:$('#ps').value},$('#pn').value,$('#pd').value||today(),$('#pt').value||nowT(),15,'Pulse saved');render()};
const CATS=[['🌿','MILD'],['⚔️','MODERATE'],['🔥','VIGOROUS']];
const STAIRS=[
// v6 (stairs refactor): ST01 "Tangga Selangkah Menara Gading" 7.26° removed: a placeholder shipped in the code (same name as ST02, no
// coordinates) that showed as the pre-selected stairway. Sessions already logged there keep their own name and data.
{"id": "ST02", "cat": "MILD", "name": "Tangga Selangkah Menara Gading", "floor": "G level", "angle": 14.25, "lat": null, "lng": null},
{"id": "ST03", "cat": "MILD", "name": "Tangga ke Dewan Mawar / Makmal Fizik (depan office)", "floor": "G level", "angle": 19.6, "lat": 5.3515422, "lng": 100.5380308},
{"id": "ST04", "cat": "MILD", "name": "Tangga dari cafe ke court tennis", "floor": "G level", "angle": 20.94, "lat": 5.3504943, "lng": 100.5389913},
{"id": "ST05", "cat": "MILD", "name": "Tangga parking KJ ke laluan study putra (belakang Jab. Matematik)", "floor": "G level", "angle": 21.8, "lat": 5.3512084, "lng": 100.5377726},
{"id": "ST06", "cat": "MILD", "name": "Tangga depan Pejabat HEP ke Makmal Kimia (tingkat 1)", "floor": "Tingkat 1", "angle": 23.96, "lat": 5.3515635, "lng": 100.5383731},
{"id": "ST07", "cat": "MILD", "name": "Tangga sebelah depan Bilik Raflesia (sebelah Seroja) ke Lab Biology", "floor": "G level", "angle": 24.45, "lat": 5.3512758, "lng": 100.5383744},
{"id": "ST08", "cat": "MILD", "name": "Tangga Makmal Inovasi ke bilik 406, 407", "floor": "G level", "angle": 24.51, "lat": null, "lng": null},
{"id": "ST09", "cat": "MILD", "name": "Tangga dari Dataran Ilmu ke Jab. Sains / Makmal Biology", "floor": "G level", "angle": 24.72, "lat": 5.3512708, "lng": 100.538078},
{"id": "ST10", "cat": "MILD", "name": "Tangga dari parking Anjung Santap ke koperasi (melalui tempat pungutan parcel)", "floor": "G level", "angle": 24.86, "lat": 5.3511202, "lng": 100.539051},
{"id": "ST11", "cat": "MILD", "name": "Tangga dari court tennis ke Blok C", "floor": "G level", "angle": 25.71, "lat": 5.3496995, "lng": 100.5390775},
{"id": "ST12", "cat": "MILD", "name": "Tangga dari Blok C ke Blok A/B", "floor": "G level", "angle": 25.85, "lat": 5.349364, "lng": 100.5390849},
{"id": "ST13", "cat": "MODERATE", "name": "Tangga belakang Dewan Ixora ke Dewan Kesidang", "floor": "G level", "angle": 26.0, "lat": 5.3502767, "lng": 100.5379339},
{"id": "ST14", "cat": "MODERATE", "name": "Tangga belakang Bilik 409 naik ke Dewan Kenanga", "floor": "G level", "angle": 26.43, "lat": 5.3524047, "lng": 100.5383392},
{"id": "ST15", "cat": "MODERATE", "name": "Tangga aras 1 naik ke bilik tutorial (sebelah Lab Biology)", "floor": "Tingkat 2", "angle": 26.57, "lat": 5.3512708, "lng": 100.538078},
{"id": "ST16", "cat": "MODERATE", "name": "Tangga merah ke wakaf / gazebo sebelah Selangkah ke Menara Gading", "floor": "G level", "angle": 26.6, "lat": null, "lng": null},
{"id": "ST17", "cat": "MODERATE", "name": "Tangga dari DS naik ke koperasi", "floor": "G level", "angle": 26.6, "lat": 5.3510194, "lng": 100.5386617},
{"id": "ST18", "cat": "MODERATE", "name": "Tangga ke Makmal Inovasi dari tapak parking depan pejabat", "floor": "G level", "angle": 27.0, "lat": 5.3520312, "lng": 100.5380334},
{"id": "ST19", "cat": "MODERATE", "name": "Tangga dari Blok Aisyah / parking Blok E ke Dewan Kenanga", "floor": "G level", "angle": 27.23, "lat": 5.3525206, "lng": 100.5386027},
{"id": "ST20", "cat": "MODERATE", "name": "Tangga sebelah rumah penjana elektrik ke Dewan Kenanga", "floor": "G level", "angle": 28.52, "lat": 5.3519878, "lng": 100.5383771},
{"id": "ST21", "cat": "MODERATE", "name": "Tangga Makmal Inovasi ke bilik 406, 407", "floor": "G level", "angle": 28.86, "lat": 5.3521864, "lng": 100.5381059},
{"id": "ST22", "cat": "MODERATE", "name": "Tangga cafe ke Dewan Melati (dewan exam) (tangga tengah)", "floor": "G level", "angle": 29.44, "lat": 5.350466, "lng": 100.5387657},
{"id": "ST23", "cat": "MODERATE", "name": "Tangga Anjung Santap", "floor": "G level", "angle": 31.2, "lat": 5.3517635, "lng": 100.5391633},
{"id": "ST24", "cat": "VIGOROUS", "name": "Tangga dalam Blok A", "floor": "G level", "angle": 31.21, "lat": 5.3490042, "lng": 100.5388927},
{"id": "ST25", "cat": "VIGOROUS", "name": "Tangga dalam Blok B", "floor": "G level", "angle": 31.3, "lat": 5.3490162, "lng": 100.5391398},
{"id": "ST26", "cat": "VIGOROUS", "name": "Tangga dari rumah pengarah naik ke Blok E", "floor": "G level", "angle": 31.52, "lat": 5.3520232, "lng": 100.5388347},
{"id": "ST27", "cat": "VIGOROUS", "name": "Tangga dari parking Anjung Santap ke koperasi (melalui tempat pungutan parcel)", "floor": "G level", "angle": 31.55, "lat": 5.3509924, "lng": 100.5388522},
{"id": "ST28", "cat": "VIGOROUS", "name": "Tangga naik ke Smart Classroom", "floor": "G level", "angle": 34.02, "lat": 5.3507487, "lng": 100.5379365},
{"id": "ST29", "cat": "VIGOROUS", "name": "Tangga naik ke Dewan Semarak", "floor": "G level", "angle": 37.2, "lat": null, "lng": null},
{"id": "ST30", "cat": "VIGOROUS", "name": "Tangga dari parking Anjung Santap ke Blok FAZ (sebelah belakang)", "floor": "G level", "angle": 37.84, "lat": 5.3511299, "lng": 100.5395432},
{"id": "ST31", "cat": "VIGOROUS", "name": "Tangga aras 1 naik ke bilik tutorial (sebelah Lab Fizik) — lower half", "floor": "Tingkat 2", "angle": 59.76, "lat": 5.3515635, "lng": 100.5383731},
{"id": "ST32", "cat": "VIGOROUS", "name": "Tangga aras 1 naik ke bilik tutorial (sebelah Lab Fizik) — upper half", "floor": "Tingkat 2", "angle": 60.13, "lat": 5.3515635, "lng": 100.5383731},
{"id": "ST33", "cat": "VIGOROUS", "name": "Tangga cafe ke Dewan Kemboja (dewan exam) (tangga hujung)", "floor": "G level", "angle": 65.52, "lat": 5.3504813, "lng": 100.5389749}
];
const stairsOf=c=>STAIRS.filter(s=>s.cat===c),hasXY=s=>s.lat!=null&&s.lng!=null,catI=()=>CATS.findIndex(c=>c[1]===STAIRS[S.loc].cat);
const PACES=[['🐢','Easy',1100,3,35],['⚔️','Moderate',850,2,65],['🔥','Vigorous',700,2,90]];
const bz=()=>{const P=PACES[S.pb.pace],c=P[3],k=S.pb.k%(2*c),n=k%c+1;return '<div class="big">'+(k<c?'INHALE ▲':'EXHALE ▼')+'</div><div class="cnt">'+Array.from({length:c},(_,i)=>'<b class="'+(i+1===n?'cur':'')+'">'+(k<c?'IN ':'OUT ')+(i+1)+'</b>').join(' — ')+'</div>'};
function tickPB(){S.pb.k++;S.pb.st=(S.pb.st||0)+1;climb();const z=$('#bz');if(z){z.innerHTML=bz();sfx(S.pb.k%(2*PACES[S.pb.pace][3])<PACES[S.pb.pace][3]?520:390,.04)}else clearInterval(S.tm)}
pages.stair=()=>{const P=PACES[S.pb.pace],q=STAIRS[S.loc];return '<h2>🧗 STAIR QUEST</h2><div class="card"><div class="row">'+CATS.map(c=>'<button class="chip '+(S.cat===c[1]?'on':'')+'" data-a="cat" data-c="'+c[1]+'">'+c[0]+' '+c[1]+'<br>'+stairsOf(c[1]).length+' stairways</button>').join('')+'</div><div class="sqlist">'+stairsOf(S.cat).map(s=>'<button class="chip '+(STAIRS[S.loc]===s?'on':'')+'" data-a="loc" data-i="'+STAIRS.indexOf(s)+'">'+'<span class="sqn">'+esc(s.name)+'</span><span class="sqf">'+esc(s.floor)+' · '+s.angle.toFixed(2)+'°</span></button>').join('')+'</div><small>📍 '+(hasXY(q)?q.lat.toFixed(7)+', '+q.lng.toFixed(7):'No coordinates recorded')+'</small><div class="row"><label>Steps per climb<input id="ss" data-in="tot" type="number" min="1"></label><label>Number of climbs<input id="sc" data-in="tot" type="number" min="1"></label></div><p>Total: <b class="big" id="tot">0</b> steps</p><div class="row"><label>Duration (min)<input id="sd" data-in="tot" type="number" min="0" step="0.5"></label><label>Pace<select id="sq">'+PACES.map(p=>'<option>'+p[1]+'</option>').join('')+'</select></label></div><div class="row"><label>Heart rate before<input id="sb" type="number" min="30" max="220"></label><label>Heart rate after<input id="sa" type="number" min="30" max="220"></label></div><div class="row"><label>Date<input id="sdt" type="date" value="'+today()+'"></label><label>Time<input id="stm" type="time" value="'+nowT()+'"></label></div><label>Notes<input id="sn"></label><button data-a="savestair">SAVE STAIR SESSION</button></div>'+
'<div class="card"><h2>PACE & BREATHE</h2><p>Choose your pace</p><div class="row">'+PACES.map((p,i)=>'<button class="chip '+(S.pb.pace===i?'on':'')+'" data-a="pace" data-i="'+i+'">'+p[0]+' '+p[1]+'</button>').join('')+'</div>PACE'+bar(P[4],'var(--grn)')+''+climber()+'<div id="bz" style="text-align:center">'+(S.pb.on?bz():'<p class="mut">Press start for the rhythm guide.</p>')+'</div><div class="row" style="margin-top:10px">'+(S.pb.on?'<button class="g" data-a="slow">SLOW DOWN</button><button data-a="pstop" style="background:var(--red);color:#fff">STOP ACTIVITY</button>':'<button data-a="pstart">START</button>')+'</div><div class="warn">Stop right away if you feel dizzy, faint, have chest pain or severe breathlessness, and seek medical attention. You never have to keep this pace.</div></div><div class="card"><h3>STAIR LOG</h3>'+(LC('stair').length?LC('stair').slice(-8).reverse().map(e=>row(e,1)).join(''):'<p class="mut">No sessions yet.</p>')+'</div>'};
INP.tot=()=>{const s=+$('#ss').value||0,c=+$('#sc').value||0,d=+$('#sd').value||0;$('#tot').textContent=s*c+(d?' ('+(s*c/d).toFixed(0)+'/min)':'')};
acts.loc=d=>{S.loc=+d.i;S.cat=STAIRS[S.loc].cat;render()};acts.cat=d=>{S.cat=d.c;S.loc=STAIRS.indexOf(stairsOf(d.c)[0]);render()};acts.pace=d=>{S.pb.pace=+d.i;if(S.pb.on)acts.pstart();else render()};
acts.pstart=()=>{S.pb.on=1;S.pb.k=0;clearInterval(S.tm);S.tm=setInterval(tickPB,PACES[S.pb.pace][2]);render()};
acts.slow=()=>{if(S.pb.pace===0){toast('Already easy. Rest if you need to.');return}S.pb.pace--;acts.pstart()};
acts.pstop=()=>{clearInterval(S.tm);S.pb.on=0;render();toast('Stopped. Rest and breathe normally.')};
acts.savestair=()=>{const s=+$('#ss').value,c=+$('#sc').value,b=+$('#sb').value,a=+$('#sa').value;if(!(s>=1&&c>=1&&c<=500)){toast('Enter steps per climb and number of climbs');return}if((b&&(b<30||b>220))||(a&&(a<30||a>220))){toast('Heart rates should be 30 to 220');return}const q=STAIRS[S.loc],d=$('#sdt').value||today(),t=$('#stm').value||nowT();add('stair',s*c,{sid:q.id,loc:q.name,diff:q.cat,floor:q.floor,angle:q.angle,lat:q.lat,lng:q.lng,steps:s,climbs:c,dur:+$('#sd').value||0,pace:$('#sq').value,hrB:b||null,hrA:a||null},$('#sn').value,d,t,25,'Stair session');render()}; // v6: no duplicate pulse entry (replaced by js/v6-stairs.js)
/* STRESS QUEST v2 - THE STORM WITHIN */
const SQP={o:'#e8742a',y:'#f2c14e',w:'#fff',k:'#2b2418',m:'#7a1f1f',v:'#c9b0f0',p:'#8767c8',t:'#2aa7a0',g:'#8a8f99',b:'#3f6fd0',c:'#9fe3f0',f:'#fff'};
const SQM={
rusher:['..o....o..','..oo..oo..','.oooooooo.','oowkoowkoo','oooooooooo','ooommmmooo','.oooooooo.','yyoo.oo.yy','y..o..o..y'],
overthinker:['..vvvvvv..','.v......v.','.v.vvvv.v.','..pppppp..','.ppwkpwkp.','.pppppppp.','.pppmmppp.','..pppppp..','..p.pp.p..'],
distractor:['..tttttt..','.tttttttt.','tttwwwwttt','ttwwkkwwtt','tttwwwwttt','.tttttttt.','.tt.gg.tt.','.tt.gg.tt.','..t.gg.t..'],
perfectionist:['y.y.yy.y.y','.yyyyyyyy.','bbbbbbbbbb','bwkbbbbwkb','bbbbbbbbbb','bbmmmmmmbb','bbbbbbbbbb','bbbbbbbbbb','.bb....bb.'],
worry:['....ff....','...ffff...','..cccccc..','.cccccccc.','.cwkccwkc.','.cccccccc.','.ccmmmmcc.','.cccccccc.','.c.cc.cc.c']};
const SQC=[
{k:'rusher',n:'RUSHER',d:'Everything feels urgent. It whispers: do it all, right now.',o:[
['🎯 Pick the ONE most important thing and start there','h','steps','Choosing one next step turns a big pile into something you can actually begin.'],
['🌬️ Take a slow breathing break','h','breathe','Slow breaths with longer exhales can ease the body’s alarm response so you can think more clearly.'],
['⚡ Work faster and skip all breaks','u',0,'Speeding up often raises pressure and mistakes. It can feel productive but tends to wear you out.'],
['📱 Check your phone first, just for a moment','s',0,'A quick distraction can feel like relief, but the pile is still waiting afterwards.'],
['😡 Tell yourself to just calm down','u',0,'Ordering yourself to relax rarely works. Something small and concrete usually helps more.']]},
{k:'overthinker',n:'OVERTHINKER',d:'It throws the same thought bubbles at you, again and again.',o:[
['🧠 Break the problem into smaller steps','h','steps','Small steps give your mind something to do instead of looping.'],
['🌬️ Take a slow breathing break','h','breathe','Breathing slowly gives your body a signal to settle, which can quiet racing thoughts.'],
['📝 Write down what is worrying you','h','write','Getting thoughts out of your head and onto paper can make them feel smaller and easier to sort.'],
['📱 Scroll endlessly to avoid thinking about it','s',0,'This may give short-term distraction, but it doesn’t address what is causing the worry.'],
['😡 Force yourself to stop thinking about it','u',0,'Pushing a thought away often makes it come back stronger. Working with it tends to help more.']]},
{k:'distractor',n:'DISTRACTOR',d:'It keeps tugging you toward anything except what matters.',o:[
['👀 Ground yourself in the room around you','h','ground','Noticing your senses brings your attention back to the present, away from the pull.'],
['🧩 Set one tiny task for the next 10 minutes','h','steps','A small, clear target is easier to start than a vague “I should focus”.'],
['🌬️ Take a slow breathing break','h','breathe','A short reset can make it easier to choose where your attention goes next.'],
['📱 Just one more video','s',0,'It can feel like a rest, but it rarely leaves you recharged and the task is still there.'],
['🙈 Pretend there’s nothing to do','u',0,'Avoiding it can bring brief relief, but worry about it usually grows in the background.']]},
{k:'perfectionist',n:'PERFECTIONIST',d:'It sets goals no one could reach, then says you failed.',o:[
['✅ Define “good enough” in 3 small steps','h','steps','A clear finish line replaces an impossible standard with something you can reach.'],
['📝 Write down what you fear will happen if it isn’t perfect','h','write','Seeing the fear in words often shows it’s smaller or less likely than it felt.'],
['🌬️ Take a slow breathing break','h','breathe','Easing your body’s tension can loosen the “it must be flawless” grip.'],
['🔁 Redo it until it’s flawless','u',0,'Endless redoing eats time and energy, and flawless is a moving target.'],
['🚪 Avoid starting at all','s',0,'Avoiding feels safe for a moment, but the stress waits and often grows.']]},
{k:'worry',n:'WORRY WISP',d:'It floats around you whispering, “What if…?”',o:[
['📝 Write the “what ifs” down, then note what you can control','h','write','Separating what you can and can’t control makes worries easier to handle.'],
['👀 Ground yourself with your five senses','h','ground','Grounding pulls your attention from imagined futures to what is real right now.'],
['🌬️ Take a slow breathing break','h','breathe','Slow breathing can calm the body’s alarm, which often softens “what if” thinking.'],
['🔮 Keep imagining the worst outcomes','u',0,'Rehearsing worst cases keeps your body on alert without solving anything.'],
['📱 Distract yourself until it fades','s',0,'This may give short-term relief, but it doesn’t address what is causing the worry.']]}];
const SQF=[['😌','Very calm'],['🙂','Calm'],['😐','Neutral'],['😟','Stressed'],['😣','Very stressed']];
const SQW=[['📚','School / assignments'],['⏰','Lack of time'],['👥','Social situations'],['🏠','Family / home'],['😴','Lack of sleep'],['💭','Overthinking'],['💰','Money / financial worries'],['❤️','Relationships'],['🩺','Health concerns'],['❓','Something else']];
const SQR=[['😣','Worse'],['😐','Same'],['🙂','A little calmer'],['😌','Much calmer']];
const GR=[[5,'👀','see'],[4,'👂','hear'],[3,'✋','feel (touch)'],[2,'👃','smell'],[1,'👅','taste']];
const TN={breathe:'🌬️ Breathing',ground:'👀 Grounding',write:'📝 Writing it down',steps:'🧩 Small steps'};
const sqk=()=>clearInterval(S.qt);
const sqc=k=>SQC.find(c=>c.k===k);
function sqScene(r,cr){const sp=((11-r)*.35).toFixed(2),sky=['#9fd8ff','#a8dcf5','#b4dcf0','#a0c4d8','#8fa8b8','#7a8896','#5f6b7a','#4a5362','#383e4c','#2b2f3a'][r-1],ps=i=>(i*37+11)%97;
let h='<div class="qs" style="background:'+sky+';--sp:'+sp+'s">';
if(r<=3)h+='<div class="qsun"></div>';
const nc=r<=2?0:Math.min(6,Math.ceil(r/2)+1);
for(let i=0;i<nc;i++)h+='<div class="qc" style="top:'+(4+i*10)+'%;--s:'+(1+i%3*.35)+';--c:'+(r>=6?'#4a4f5c':'#fff')+';animation-duration:'+(Math.max(8,50-r*4)+i*4)+'s;animation-delay:-'+i*7+'s"></div>';
if(r>=5)for(let i=0;i<r-3;i++)h+='<i class="qw" style="top:'+(10+ps(i)%70)+'%;animation-duration:'+(Math.max(.6,3-r*.25)+i*.1)+'s;animation-delay:-'+i*.4+'s"></i>';
if(r>=6)for(let i=0;i<(r-4)*6;i++)h+='<i class="qd" style="left:'+ps(i+3)+'%;animation-duration:'+Math.max(.5,1.1-r*.06)+'s;animation-delay:-'+(ps(i)%10)/10+'s"></i>';
if(r>=8)h+='<div class="qlt"></div>';
if(r<=4)for(let i=0;i<8;i++)h+='<i class="qf" style="left:'+(6+ps(i)*.9)+'%;top:'+(45+ps(i+5)%40)+'%;animation-delay:-'+i*.3+'s"></i>';
if(r<=3)h+='<i class="qb" style="top:18%"></i><i class="qb" style="top:30%;animation-delay:-4s"></i>';
[4,22,70,88].forEach((x,i)=>h+='<div class="qtr" style="left:'+x+'%;animation-delay:-'+i*.2+'s"></div>');
const n=r>=9?3:r>=7?2:r>=4?1:0;(cr||[]).slice(0,n).forEach((k,i)=>h+='<div class="qcr" style="left:'+(14+i*28)+'%;top:'+(22+i*14)+'%;animation-duration:'+(.3+(11-r)*.07)+'s">'+spr(SQM[k],SQP,3)+'</div>');
return h+'<div class="qh">'+HERO(4)+'</div></div>'}
function sqMeter(r){return '<div class="qmh">🧠 STRESS</div><div class="qmb"><b class="qmk" style="left:'+((r-1)/9*100)+'%">●</b></div><div class="qml"><span>CALM</span><span>HIGH</span></div><div class="qmn">CURRENT STRESS: '+r+'/10</div>'}
function sqKit(){const T={};st.e.filter(e=>e.c==='stress'&&e.m.tech).forEach(e=>e.m.tech.forEach(x=>{const o=T[x.t]=T[x.t]||[0,0];o[0]++;if(x.fb>=2)o[1]++}));const k=Object.keys(T);if(!k.length)return'';return '<div class="card"><h3>🧰 WHAT HELPS YOU</h3>'+k.sort((a,b)=>T[b][1]/T[b][0]-T[a][1]/T[a][0]).map(t=>'<div>'+TN[t]+': helped '+T[t][1]+' of '+T[t][0]+bar(T[t][1]/T[t][0]*100,'var(--grn)')+'</div>').join('')+'<small>Based only on your own ratings.</small></div>'}
